// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dftvdetlnlocvfdmfrrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmdHZkZXRsbmxvY3ZmZG1mcnJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwNTc3MDcsImV4cCI6MjA1MjYzMzcwN30.kHkgxytoKQHMgZkGFpvceMJv0tMaOigtV-VeqZkPKkg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);